# Generated by Django 3.2.5 on 2021-07-26 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0001_initial'),
        ('aplicatie2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplicatie1.location'),
            preserve_default=False,
        ),
    ]
